### ISSUE TITLE
App Installation Failed: Unable to install "MyApp"

### ISSUE THREAD

**Issue by radmakr** [breez/breez-sdk-liquid-swift#4]
Hi Breez team,

I'll start by saying I do not have any rust experience. Or experience with Swift packages that pull in xcframeworks as remote binary targets.
I am trying to pull the package into my iOS app via Xcode's Swift Package Manager integration following the steps in the readme. The project compiles and builds successfully but when I try to run in the simulator I am met with the following error,

> Please try again later. Failed to load Info.plist from bundle at path /Users/rademaker/Library/Developer/CoreSimulator/Devices/675B24F7-CDFD-4864-8C67-D3EFE6C7A4CE/data/Library/Caches/com.apple.mobile.installd.staging/temp.la9Twk/extracted/MyApp.app/Frameworks/breez_sdk_liquidFFI.framework; Extra info about "/Users/rademaker/Library/Developer/CoreSimulator/Devices/675B24F7-CDFD-4864-8C67-D3EFE6C7A4CE/data/Library/Caches/com.apple.mobile.installd.staging/temp.la9Twk/extracted/MyApp.app/Frameworks/breez_sdk_liquidFFI.framework/Info.plist": Couldn't stat /Users/rademaker/Library/Developer/CoreSimulator/Devices/675B24F7-CDFD-4864-8C67-D3EFE6C7A4CE/data/Library/Caches/com.apple.mobile.installd.staging/temp.la9Twk/extracted/MyApp.app/Frameworks/breez_sdk_liquidFFI.framework/Info.plist: No such file or directory

I _think_ the xcframework binary target isn't getting built? But I really don't know. Is your team experiencing this as well? If not, am I doing something wrong integrating this into my app? 

Thanks for any info you can give me.

**Comment by mattmassicotte** [comment]
I just downloaded the XCFramework at "https://github.com/breez/breez-sdk-liquid-swift/releases/download/0.2.0/breez_sdk_liquidFFI.xcframework.zip".

It contains three `.framework` bundles, none of which have embedded Info.plist files. I just quickly poked around with otool and they look like valid dylibs. So, I think there is a packaging issue going on. These are technically not `.framework` bundles but they probably can be used as dylibs.

**Comment by FlorianHubl** [comment]
Okay so the package is currently unusable. When will this package error be fixed?

**Comment by FlorianHubl** [comment]
I still get an error when I try to import the package and run it on a simulator.
<img width="464" alt="Bildschirmfoto 2024-10-26 um 15 16 21" src="https://github.com/user-attachments/assets/5b08e06a-e15b-41e2-9c2f-34acbdf392d2">

**Comment by dangeross** [comment]
@FlorianHubl we need to build a new release first. We'll do so next week and let you know when it's available.

**Comment by roeierez** [comment]
@FlorianHubl we have just published 0.5.0-rc3. Can you please test that?

**Comment by FlorianHubl** [comment]
I imported the newest version of the package using the Swift Package Manager but when I try to run it on a simulator I still got this error.
<img width="468" alt="Bildschirmfoto 2024-11-04 um 22 13 57" src="https://github.com/user-attachments/assets/97819aaa-3b17-4b22-be48-ba36e2eeeaef">

**Comment by dangeross** [comment]
@FlorianHubl I've created a test repo here: https://github.com/dangeross/nodeless-swift-test

Can you test if it runs for you? You need to set the BREEZ_API_KEY and MNEMONIC in the NodeTestApp.swift file and it should output in the log the pubkey.

I created a new Swift project, added this repo as a package dependency with version 0.5.0-rc4, then linked the BreezSDKLiquid binary as below:
<img width="1255" alt="Screenshot 2024-11-06 at 08 53 36" src="https://github.com/user-attachments/assets/0945decd-d9fc-45cb-9076-16d74e1b2608">

**Comment by FlorianHubl** [comment]
Thank you it worked. The problem was that I downloaded the wrong version of the package.
